use_frameworks!

platform :ios, '8.0'

target 'OCPromise_Example' do
  pod 'OCPromise', :path => '../'

  target 'OCPromise_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
